site_name: Mozilla Data Collective Python SDK
repo_url: https://github.com/Mozilla-Data-Collective/datacollective-python
repo_name: datacollective-python

nav:
  - Home: index.md
  - Programmatic Uploads: upload.md
  - Schema-Based Loading:
    - How it works: schema_documentation.md
    - Adding a New Schema: add_new_schema.md
    - Migrating Schemas to 0.6.0: schema_migration_0.6.0.md
    - Extending the Loading Logic: extend_schema_loading_logic.md
    - Loading Strategies:
      - Index: loaders/index.md
      - Multi-split: loaders/multi_split.md
      - Multi-sections: loaders/multi_sections.md
      - Paired-glob: loaders/paired_glob.md
      - Glob: loaders/glob.md
  - API Reference: api.md
  - Internal Development:
    - Library Development: library_development.md
    - Release Workflow: release.md

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: docs/mdc_logo.png
  favicon: docs/mdc_ccc.png
  extra_css:
    - assets/custom.css
  features:
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
